### ISSUE TITLE
How to install that?

### ISSUE THREAD

**Issue by robotnic** [xmpp-ftw/xmpp-ftw-vcard#3]
npm i --save xmpp-ftw-vcard
npm http GET https://registry.npmjs.org/xmpp-ftw-vcard
npm http 404 https://registry.npmjs.org/xmpp-ftw-vcard
npm ERR! 404 404 Not Found: xmpp-ftw-vcard
npm ERR! 404 
npm ERR! 404 'xmpp-ftw-vcard' is not in the npm registry.

**Comment by lloydwatkin** [comment]
Hey,

Unfortunately I haven't completed xmpp-ftw-vcard hence its still not in the registry. Happy to accept pull requests if you are interested in this code, otherwise I could potentially look at getting it implemented next week.

**Comment by triniwiz** [comment]
@lloydwatkin can't wait to see it in the reg ^_^
